# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Convert and Publish

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  convert:
    name: Convert
    runs-on: ubuntu-latest
    permissions:
        contents: write  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert
        run: ./.bin/publish.sh
